services:
  postgres-test:
    image: postgres:16
    container_name: saldoify-test-db
    ports:
      - "5437:5432"  # Using port 5437 to avoid conflicts with dev DB on 5436
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: saldoify_test
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-test-data: