services:
  postgres:
    image: postgres:16-alpine
    container_name: saldoify-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: saldoify
      POSTGRES_PASSWORD: saldoify_password
      POSTGRES_DB: saldoify
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saldoify"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: node:20-alpine
    container_name: saldoify-app-dev
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      DATABASE_URL: postgresql://saldoify:saldoify_password@postgres:5432/saldoify
      NODE_ENV: development
    volumes:
      # Mount source code for live reload
      - .:/app
      # Use named volume for node_modules to avoid conflicts
      - node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data_dev:
  node_modules: