// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: liquid_assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountLiquidAssets = `-- name: CountLiquidAssets :one
SELECT COUNT(*) FROM liquid_assets WHERE user_id = $1
`

func (q *Queries) CountLiquidAssets(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, CountLiquidAssets, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateLiquidAsset = `-- name: CreateLiquidAsset :one
INSERT INTO liquid_assets (id, user_id, asset_type, name, description, current_value, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, asset_type, name, description, current_value, created_at, updated_at
`

type CreateLiquidAssetParams struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	AssetType    string             `json:"asset_type"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	CurrentValue pgtype.Numeric     `json:"current_value"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateLiquidAsset(ctx context.Context, arg *CreateLiquidAssetParams) (*LiquidAsset, error) {
	row := q.db.QueryRow(ctx, CreateLiquidAsset,
		arg.ID,
		arg.UserID,
		arg.AssetType,
		arg.Name,
		arg.Description,
		arg.CurrentValue,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LiquidAsset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AssetType,
		&i.Name,
		&i.Description,
		&i.CurrentValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeleteLiquidAsset = `-- name: DeleteLiquidAsset :exec
DELETE FROM liquid_assets WHERE id = $1
`

func (q *Queries) DeleteLiquidAsset(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, DeleteLiquidAsset, id)
	return err
}

const GetLiquidAssetByID = `-- name: GetLiquidAssetByID :one
SELECT id, user_id, asset_type, name, description, current_value, created_at, updated_at FROM liquid_assets WHERE id = $1
`

func (q *Queries) GetLiquidAssetByID(ctx context.Context, id string) (*LiquidAsset, error) {
	row := q.db.QueryRow(ctx, GetLiquidAssetByID, id)
	var i LiquidAsset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AssetType,
		&i.Name,
		&i.Description,
		&i.CurrentValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetLiquidAssetsByUserID = `-- name: GetLiquidAssetsByUserID :many
SELECT id, user_id, asset_type, name, description, current_value, created_at, updated_at FROM liquid_assets 
WHERE user_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) GetLiquidAssetsByUserID(ctx context.Context, userID string) ([]*LiquidAsset, error) {
	rows, err := q.db.Query(ctx, GetLiquidAssetsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*LiquidAsset{}
	for rows.Next() {
		var i LiquidAsset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AssetType,
			&i.Name,
			&i.Description,
			&i.CurrentValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetLiquidAssetsByUserIDAndType = `-- name: GetLiquidAssetsByUserIDAndType :many
SELECT id, user_id, asset_type, name, description, current_value, created_at, updated_at FROM liquid_assets 
WHERE user_id = $1 AND asset_type = $2 
ORDER BY created_at DESC
`

type GetLiquidAssetsByUserIDAndTypeParams struct {
	UserID    string `json:"user_id"`
	AssetType string `json:"asset_type"`
}

func (q *Queries) GetLiquidAssetsByUserIDAndType(ctx context.Context, arg *GetLiquidAssetsByUserIDAndTypeParams) ([]*LiquidAsset, error) {
	rows, err := q.db.Query(ctx, GetLiquidAssetsByUserIDAndType, arg.UserID, arg.AssetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*LiquidAsset{}
	for rows.Next() {
		var i LiquidAsset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AssetType,
			&i.Name,
			&i.Description,
			&i.CurrentValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetLiquidAssetsTotalValue = `-- name: GetLiquidAssetsTotalValue :one
SELECT COALESCE(SUM(current_value), 0) as total_value 
FROM liquid_assets 
WHERE user_id = $1
`

func (q *Queries) GetLiquidAssetsTotalValue(ctx context.Context, userID string) (interface{}, error) {
	row := q.db.QueryRow(ctx, GetLiquidAssetsTotalValue, userID)
	var total_value interface{}
	err := row.Scan(&total_value)
	return total_value, err
}

const ListLiquidAssets = `-- name: ListLiquidAssets :many
SELECT id, user_id, asset_type, name, description, current_value, created_at, updated_at FROM liquid_assets 
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLiquidAssetsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListLiquidAssets(ctx context.Context, arg *ListLiquidAssetsParams) ([]*LiquidAsset, error) {
	rows, err := q.db.Query(ctx, ListLiquidAssets, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*LiquidAsset{}
	for rows.Next() {
		var i LiquidAsset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AssetType,
			&i.Name,
			&i.Description,
			&i.CurrentValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateLiquidAsset = `-- name: UpdateLiquidAsset :one
UPDATE liquid_assets 
SET asset_type = $2, name = $3, description = $4, current_value = $5, updated_at = $6
WHERE id = $1
RETURNING id, user_id, asset_type, name, description, current_value, created_at, updated_at
`

type UpdateLiquidAssetParams struct {
	ID           string             `json:"id"`
	AssetType    string             `json:"asset_type"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	CurrentValue pgtype.Numeric     `json:"current_value"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateLiquidAsset(ctx context.Context, arg *UpdateLiquidAssetParams) (*LiquidAsset, error) {
	row := q.db.QueryRow(ctx, UpdateLiquidAsset,
		arg.ID,
		arg.AssetType,
		arg.Name,
		arg.Description,
		arg.CurrentValue,
		arg.UpdatedAt,
	)
	var i LiquidAsset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AssetType,
		&i.Name,
		&i.Description,
		&i.CurrentValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
